version: '3'

services:
  django:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - pgdb


  pgdb:
    image: postgres
    restart: always
    container_name: pgdb
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - django
    restart: always







