# Generated by Django 5.0.6 on 2024-06-27 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_ky', models.TextField(null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('question_en', models.TextField(null=True, verbose_name='Question')),
                ('question_ru', models.TextField(null=True, verbose_name='Question')),
                ('question_ky', models.TextField(null=True, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_en', models.TextField(null=True, verbose_name='Answer')),
                ('answer_ru', models.TextField(null=True, verbose_name='Answer')),
                ('answer_ky', models.TextField(null=True, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('name_ky', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('speciality', models.CharField(max_length=100, verbose_name='Speciality')),
                ('speciality_en', models.CharField(max_length=100, null=True, verbose_name='Speciality')),
                ('speciality_ru', models.CharField(max_length=100, null=True, verbose_name='Speciality')),
                ('speciality_ky', models.CharField(max_length=100, null=True, verbose_name='Speciality')),
                ('education', models.TextField(verbose_name='Education')),
                ('education_en', models.TextField(null=True, verbose_name='Education')),
                ('education_ru', models.TextField(null=True, verbose_name='Education')),
                ('education_ky', models.TextField(null=True, verbose_name='Education')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_ky', models.TextField(null=True, verbose_name='Description')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilimkana_api.category')),
            ],
        ),
    ]
