# Generated by Django 5.0.6 on 2024-07-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilimkana_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ky',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='description',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
