# Generated by Django 5.0.6 on 2024-06-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilimkana_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение в base64'),
        ),
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение в base64'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение в base64'),
        ),
    ]
