# Generated by Django 5.0.6 on 2024-06-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilimkana_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(blank=True, null=True, verbose_name='Изображение BASE64')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_en', models.TextField(null=True, verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('text_ky', models.TextField(null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(blank=True, null=True, verbose_name='Изображение BASE64')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_en', models.TextField(null=True, verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('text_ky', models.TextField(null=True, verbose_name='Текст')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение в base64'),
        ),
        migrations.AlterField(
            model_name='program',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение в base64'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение в base64'),
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=300, verbose_name='Фамилие')),
                ('number', models.CharField(max_length=150, verbose_name='Номер')),
                ('email', models.EmailField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bilimkana_api.category')),
            ],
        ),
    ]
